### ISSUE TITLE
[BUG] Main entrance window panes

### ISSUE THREAD

**Issue by amgmacht** [Keihaan382/rockfordhills_dp_phase2#1]
https://prnt.sc/6wOQ-3J8HuLo

At the main entrance you can walk through the 4 windows from the outside and I was able to lock the doors.

can you still fix this for this Phase2 version?

**Comment by Keihaan382** [comment]
Hi... I'll check it out. Yes, I can update the YBN of the collision. Don't worry, thank you very much for letting me know. I knew about that, but it happened to me, and I completely forgot to put the collision.

**Comment by amgmacht** [comment]
no problem all good ^^ but it would be super cool if you can fix it anyway.

**Comment by Keihaan382** [comment]
yes, today I update it when I return from work. I will notify you here. Thanks a lot.

**Comment by Keihaan382** [comment]
@amgmacht 
collision repaired, you can directly download the bh1_07_0.ybn file from the [ybn] folder.
Replace your stream file.

Directory:
rockfordhills_dp_phase2/K382_RockfordHills_dp_Fase02/stream/[ybn]
